### ISSUE TITLE
Download file link is broken

### ISSUE THREAD

**Issue by tliontis** [hitaandrea/MGcount#1]
"Alternatively can download the latest release as a binary executable file here."

But "here" redirects to a broken link: https://github.com/hitaandrea/MGcount/releases/download/1.0.0-beta/MGcount

I assume it should redirect instead to: https://github.com/hitaandrea/MGcount/releases/

**Comment by hitaandrea** [comment]
Just updated the link to the current release. Thanks for pointing this out!
