### ISSUE TITLE
cannot run with C elegans gtf

### ISSUE THREAD

**Issue by tliontis** [hitaandrea/MGcount#2]
Hi,

I am having difficulty running the program. 
I am running:
`MGcount --gtf /_path_/Caenorhabditis_elegans.WBcel235.custom.gtf --bam_infiles /_path_/MGcount_bamfiles.txt --outdir MGcount -s 1`
There is an error at the initial phase and then it looks like featureCounts is called repeatedly, and the program keeps running with failure:
![error1](https://user-images.githubusercontent.com/90729007/150461714-b6ab1b2c-1d16-496c-8ead-04330a90b5f4.png)

![error2](https://user-images.githubusercontent.com/90729007/150461721-8c3201e7-be77-441c-be81-c4cf9ba700a2.png)

![error3](https://user-images.githubusercontent.com/90729007/150461727-d50d7ca1-a64b-4842-a1ea-af64741cfb5d.png)

error text: " sh: 1: Primers/RNAseq/mgcount_tutorial/MGcount/.mg_4dc7m91w/dotced_1.clean_Aremoved_counts_small.csv: not found
sh: 1: Primers/RNAseq/mgcount_tutorial/MGcount/.mg_4dc7m91w/small_annot.gtf: not found "
+
" READ ASSIGNATION FAILED. Please check that:
1. The gtf contains the required non-empty fields as defined by the assignation arguments "feature", "feature_output" & "feature_biotype2. featureCounts is available on the path specified by --featureCounts_path argument (default: /user/bin/featureCounts)
3. Input bam files are not empty or corrupted "

After troubleshooting for a while I am not sure what to do. I generated the BAM files with ShortStack and have validated their results with other counting programs like QuasR and DESEQ2 so the BAM files are unlikely to be corrupted. Furthermore, I'm using the custom C elegans gtf file provided by MGcount. As for featureCounts, it is executable and clearly MGcount is able to call it. I can also run featureCounts by typing it in the command line (it is in /usr/bin/). 

Furthermore, in the output directory, there is a copy of my .bam files and a "short" and "long" .gff-looking file.

**Comment by hitaandrea** [comment]
Hi,

Let me try to reproduce your error. It looks like there is a problem with the gtf small non-coding annotations extraction during the first assignation round.

When you see this "small" .gtf-looking file in your output directory, you see this in the first level of the folder or you see this inside a temporary subdirectory named ".mg_4dc7m91w" as specified by the error message: Primers/RNAseq/mgcount_tutorial/MGcount/*.mg_4dc7m91w*/small_annot.gtf: not found ?

Also, have you tried to run the program as a python module? If so, are you getting the exact same error?

**Comment by tliontis** [comment]
Thank you for helping me with this.
The "small_annot.gtf" and "long_annot.gtf" as well as a copy of my bam files get created inside a temporary directory .mg file. I ran the code through the python module and got similar errors:
![error4](https://user-images.githubusercontent.com/90729007/150577398-18356aeb-4502-40bd-8710-89beed077978.png)
The file name in 
"Primers/RNAseq/MGcount/.mg_6lpu82qy/small_annot.gtf: not found" seems to be caused by a space in my absolute path, because this same .mg_6lpu82qy/small_annot.gtf exists, but the path is longer and does not begin at "Primers". Using a path without spaces resolves this error, but does not resolve the second error:
"sh: 1: Primers/RNAseq/MGcount/.mg_49u7c5bv/ced_1.clean_Aremoved_counts_small.csv: not found"

I tried running the code with relative paths (since I don't have any spaces starting at /RNAseq/...) but this leads to the same kind of error because I believe the file with bam file paths (bam_files.txt) is expecting absolute paths.

Finally, I tried escaping the space symbols with \ in the bam_files.txt, but this leads to a different error, probably related to character parsing within python: 
![error5](https://user-images.githubusercontent.com/90729007/150580073-339e60a6-d229-4a8c-9e67-09926552bcfd.png)

**Comment by tliontis** [comment]
Making sure that paths in --ourdir argument and in the input bam file .txt file have **NO SPACES** seems to resolve the problem!
I recommend including this topic as a Bug until resolved. For example, I cannot use my cloud storage because it has an obligatory space in its absolute path.

**Comment by hitaandrea** [comment]
Many thanks for spotting the issue with spaces on paths. Looking forward to resolve this in the coming days ;)

**Comment by hitaandrea** [comment]
Hi @tliontis, I uploaded a new maintenance release addressing this issue. Please, let me know if you encounter any problem.
